"""
Main Entry Point
CLI interface untuk chatbot

Auto-generated by migrate_chatbot.py
Date: 2025-10-17 21:16:19
"""

#!/usr/bin/env python3

import sys
from core.chatbot import ToysShopChatbot
from utils.helpers import load_products_from_db
from utils.testing import test_chatbot_scenarios
from utils.exporter import export_metrics_for_thesis


def main():
    """Main entry point"""
    
    if len(sys.argv) > 1:
        command = sys.argv[1].lower()
        
        if command == 'test':
            test_chatbot_scenarios()
            return
        
        elif command == 'metrics':
            export_metrics_for_thesis()
            return
        
        elif command == 'help':
            print("""
GA TOYS CHATBOT - COMMAND LINE OPTIONS

Usage: python main.py [command]

Commands:
    (no command)    Run interactive chatbot
    test           Run automated test scenarios
    metrics        Export metrics report for thesis
    help           Show this help message

Examples:
    python main.py
    python main.py test
    python main.py metrics
            """)
            return
    
    # Default: Run interactive chatbot
    chatbot = ToysShopChatbot()
    
    if not chatbot.initialize():
        print("\n[FATAL] Failed to initialize chatbot. Exiting.")
        return
    
    chatbot.run_interactive()

if __name__ == "__main__":
    main()
