"""
Embedding Factory

Auto-generated by migrate_chatbot.py
Date: 2025-10-17 21:16:19
"""

from core.config import EMBEDDING_MODEL, EMBEDDING_MODEL_TYPE
from .sentence_transformer import SentenceTransformerEmbedding

def get_embedding_model():
    """Factory function to get embedding model"""
    if EMBEDDING_MODEL_TYPE == "sentence-transformers":
        return SentenceTransformerEmbedding(model_name=EMBEDDING_MODEL)
    else:
        return SentenceTransformerEmbedding(model_name=EMBEDDING_MODEL)
