"""
Base Embedding Interface
Abstract class untuk embedding models

Auto-generated by migrate_chatbot.py
Date: 2025-10-17 21:16:19
"""

from abc import ABC, abstractmethod
from typing import List

class BaseEmbedding(ABC):
    """Abstract base class for embeddings"""
    
    @abstractmethod
    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """Embed multiple documents"""
        pass
    
    @abstractmethod
    def embed_query(self, text: str) -> List[float]:
        """Embed single query"""
        pass
    
    def __call__(self, text: str) -> List[float]:
        return self.embed_query(text)
