# """
# BGE-M3 Embedding Implementation

# Auto-generated by migrate_chatbot.py
# Date: 2025-10-17 21:16:19
# """

# from FlagEmbedding import BGEM3FlagModel
# from .base import BaseEmbedding
# from typing import List

# class BGEM3Embedding(BaseEmbedding):
#     """BGE-M3 model wrapper"""
    
#     def __init__(self, model_name: str = "BAAI/bge-m3", 
#                  use_fp16: bool = True, 
#                  max_length: int = 8192):
#         print(f"[INIT] Loading BGE-M3: {model_name}")
#         self.model = BGEM3FlagModel(model_name, use_fp16=use_fp16)
#         self.max_length = max_length
#         print(f"[SUCCESS] BGE-M3 loaded")
    
#     def embed_documents(self, texts: List[str]) -> List[List[float]]:
#         embeddings = self.model.encode(
#             texts,
#             batch_size=1,
#             max_length=self.max_length
#         )
#         if isinstance(embeddings, dict):
#             embeddings = embeddings['dense_vecs']
#         return embeddings.tolist()
    
#     def embed_query(self, text: str) -> List[float]:
#         embedding = self.model.encode(
#             [text],
#             batch_size=1,
#             max_length=self.max_length
#         )
#         if isinstance(embedding, dict):
#             embedding = embedding['dense_vecs']
#         return embedding[0].tolist()
