"""
SentenceTransformer Embedding Implementation

Auto-generated by migrate_chatbot.py
Date: 2025-10-17 21:16:19
"""

from langchain_community.embeddings import SentenceTransformerEmbeddings
from .base import BaseEmbedding
from typing import List

class SentenceTransformerEmbedding(BaseEmbedding):
    """Wrapper for SentenceTransformer models"""
    
    def __init__(self, model_name: str):
        print(f"[INIT] Loading SentenceTransformer: {model_name}")
        self.model = SentenceTransformerEmbeddings(model_name=model_name)
        print(f"[SUCCESS] Model loaded")
    
    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        return self.model.embed_documents(texts)
    
    def embed_query(self, text: str) -> List[float]:
        return self.model.embed_query(text)
